	<body>
	<center>
		<h1>Grand in-page Title displaying My Amazing Company Logo</h1>
	</center>
	<hr>
	<h1>Five reason why Assignment 01 is soo lame:</h1>
	<ul>
		<li>Preformed a software re-install on my laptop on Saturday</li>
		<li>Download and became re-aquinted with required software which helps in writing code</li>
		<li>Working with Ms. Mavis Beacon to improve my typing for a job application</li>
		<li>CSS was never second nature and have to work with that aspect</li>
		<li>Getting Git, brand new to me even though I knew it was out there I never used it</li>
	</ul>
	<p>Those are my excuses without a real reason, I know.</p>