<?php

	$siteClients = [
		// uniformed array objects - manipulate each array object in the same manner
		[ "registeredClient" => "Peggy", "gender" => "Female", "userName" => "Big Peg", "currentStatus" => "Looking", "updatedStatus" => "3/14/14"],
		[ "registeredClient" => "Al", "gender" => "Male", "userName" => "All Al", "currentStatus" => "Looking", "updatedStatus" => "2/20/14"],
		[ "registeredClient" => "Fred", "gender" => "Male", "userName" => "Freddy", "currentStatus" => "Unavailable, at the moment", "updatedStatus" => "1/25/14" ],
		[ "registeredClient" => "Sue", "gender" => "Female", "userName" => "Sue Me", "currentStatus" => "Looking", "updatedStatus" => "2/10/14"],

	];

?>